{application,idna,
             [{description,"A pure Erlang IDNA implementation"},
              {vsn,"1.1.0"},
              {modules,[idna,idna_ucs,idna_unicode,idna_unicode_data,
                        punycode]},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {maintainers,["Benoit Chesneau"]},
              {license,["BSD"]},
              {links,[{"Github","https://github.com/benoitc/erlang-idna"}]}]}.
